- name: Setup Node.js
  uses: actions/setup-node@v3
  with:
    node-version: '16'

- name: Install Mabl CLI
  run: npm install -g @mablhq/mabl-cli

- name: Verify CLI Installed
  run: mabl --version

- name: Run Mabl Plan
  run: mabl test run --plan-id rrfp3xJevkiRdqJwjyoZ5Q-w --api-key ${{ secrets.MABL_API_KEY }}
