name: Run Mabl Tests on Push

on:
  push:
    branches:
      - main

jobs:
  run-mabl-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install Mabl CLI
        run: curl -s https://app.mabl.com/install/mabl-cli-linux | bash

      - name: Run Mabl Plan
        run: ./mabl-cli test run --plan-id <rrfp3xJevkiRdqJwjyoZ5Q-w> --api-key ${{ secrets.MABL_API_KEY }}
